### ISSUE TITLE
ContextMenu has incorrect position in Internet Explorer

### ISSUE THREAD

**Issue by jannikweise** [TobitSoftware/chayns-components#107]
The position of the item rendered by the ContextMenu component is not correct in Internet Explorer. It will be displayed in the top left corner of the page instead near to the trigger element.

I use the component as in the following example:
```javascript
<ContextMenu
    onChildrenClick={this.handleShowContextMenu}
    onLayerClick={this.handleHideContextMenu}
    items={contextMenuItems}
    hide={!showContextMenu}
/>
```

**Comment by JonasGossens** [comment]
I fixed this issue in version 4.2.3. The problem was, that Internet Explorer don't provides x and y props in the rect object.
