### ISSUE TITLE
Issue with "writeDay"

### ISSUE THREAD

**Issue by niklasschemmer** [TobitSoftware/chayns-components#140]
Hi,
the writeDay prop display the day one ahead.
On a friday for example it says "Samstag, Heute", this error continues for every day.
Might have to do with the sunday being the "0" when fetched from the date object.
Try this: "new Date('Sun Sep 22 2019').getDay() => 0".

**Comment by JonasGossens** [comment]
Hi Niklas,
thanks for your bug report. Now, I fixed this problem in version 4.12.5.
