### ISSUE TITLE
Add option to DateInfo component to hide year

### ISSUE THREAD

**Issue by leodr** [TobitSoftware/chayns-components#155]
The DateInfo component should have an option to hide the year, or show a shortened version of the year (19, instead of 2019).

**Comment by JonasGossens** [comment]
Hi Leonhard,
I added the feature in v4.13.0. It's possible to hide or shorten the year of the date. 

You can find further informations in the component documentation: https://github.com/TobitSoftware/chayns-components/tree/master/src/react-chayns-dateinfo
