### ISSUE TITLE
It is currently impossible to give Icons a predefined chayns color

### ISSUE THREAD

**Issue by leodr** [TobitSoftware/chayns-components#156]
When using the Icon component with one of the chayns__color-- color classes, the default color of the Icon overrides the color class.

**Comment by JonasGossens** [comment]
Hi Leonhard,
it's still possible to override the color class of a button using important color classes. Important color classes have an "i" at the end. It's documented in the css wiki: https://github.com/TobitSoftware/chayns-css/wiki/Classes-&-Colors#site-color
