### ISSUE TITLE
Using deprecated proptypes

### ISSUE THREAD

**Issue by ST-bschulze** [TobitSoftware/chayns-components#25]
Due to the use of deprecated PropTypes (since React version v15.5) an error message occures in the browser console.
Should be using the [prop-types library](https://www.npmjs.com/package/prop-types).

**Comment by braun-michael** [comment]
The chayns-components were updated to use the [prop-types](https://github.com/facebook/prop-types) and [react-transition-group](https://github.com/reactjs/react-transition-group) packages.
The changes are released with [Version 1.1.0](https://github.com/TobitSoftware/chayns-components/tree/v1.1.0)
