### ISSUE TITLE
import directly from 'tobit-chayns_components'

### ISSUE THREAD

**Issue by kmathmann** [TobitSoftware/chayns-components#37]
`import { Accordion } from 'tobit-chayns_components'`

should be similar to 

`import Accordion from 'tobit-chayns_components/react-chayns-accordion';'`

**Comment by braun-michael** [comment]
It is released in version 2 of the chayns-components. You could import every component directly from the chayns-components package.

Take a look at the [migration guide](https://github.com/TobitSoftware/chayns-components/blob/v2.0.0/migrating.md) for further informations.
