### ISSUE TITLE
remove input inline styles

### ISSUE THREAD

**Issue by kmathmann** [TobitSoftware/chayns-components#39]
Remove the styles `width: '100%'` and ` marginBottom: '5px'` from the normal Input Component.

These styles are not included into the chayns-css api styles. So they should not be added to the input tag next to the chayns-css classes.

**Comment by braun-michael** [comment]
The default styles are removed in version 2 of the chayns-components.

Take a look at the [migration guide](https://github.com/TobitSoftware/chayns-components/blob/v2.0.0/migrating.md) to see what you have to change to upgrade.
