### ISSUE TITLE
Accordion Badge

### ISSUE THREAD

**Issue by niklasschemmer** [TobitSoftware/chayns-components#41]
The Accordion Components badge property should accept jsx or html too, because its often nessecary to render an icon or sth similar.

**Comment by niklasschemmer** [comment]
Additionally there is a bug, when i set the badge prop, react throws a warning, saying each child in an iterator or array should have a key prop.

**Comment by braun-michael** [comment]
The PropTypes of the Accordion-Component were updated. You should be able to use React-Nodes in the badge-prop in the latest version of ChaynsComponents.
The React-Warning was fixed too: When a badge is specified, the head-prop will be wrapped in a span-tag with a key.
