### ISSUE TITLE
minHeight on SetupWizard

### ISSUE THREAD

**Issue by KaiSchniggendiller** [TobitSoftware/chayns-components#51]
it should be possible to set a minHeight to the SetupWizard component

**Comment by braun-michael** [comment]
On which element do you want to set the style (minHeight)-prop? On the sw__top or the sw__content element?

**Comment by KaiSchniggendiller** [comment]
thx for the quick reply

**Comment by braun-michael** [comment]
It is released in version 2 of the chayns-components.

Take a look at the [migration guide](https://github.com/TobitSoftware/chayns-components/blob/v2.0.0/migrating.md) to see what you have to change to upgrade.
