### ISSUE TITLE
Accordion badgeColor

### ISSUE THREAD

**Issue by KaiSchniggendiller** [TobitSoftware/chayns-components#52]
it should be possible to set an optional badgeColor to an accordion

**Comment by KaiSchniggendiller** [comment]
thx for the very quick reply

**Comment by braun-michael** [comment]
It is released in version 2 of the chayns-components.

Take a look at the [migration guide](https://github.com/TobitSoftware/chayns-components/blob/v2.0.0/migrating.md) to see what you have to change to upgrade.
