### ISSUE TITLE
status nach dem reload

### ISSUE THREAD

**Issue by uvalmsick** [TobitSoftware/chayns-components#8]
Wenn ich den Modeswitch einbaue, sollte nach dem neuladen der Seite das system sich an den alten status errinnern und die vorherige Ansicht anzeigen

**Comment by pjanning** [comment]
German issues? 🤔

**Comment by uvalmsick** [comment]
Dont bei so Germany... 😉

**Comment by braun-michael** [comment]
When there were no uac-groups specified for a mode this mode was not selected after the page loaded.
This problem should be solved in **version 1.0.40**.
